- run: npm run build
- uses: peaceiris/actions-gh-pages@v3
  with:
    personal_token: ${{ secrets.DEPLOY_TOKEN }}
    external_repository: piotereks/piotereks
    publish_dir: ./parking-deploy/docs/html/parking  # Keep your vite config as-is
    destination_dir: docs/html/parking
